// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOdj0nyVctktwBgQU3RQDiq-FpfXS2bY',
    appId: '1:123422089993:android:8bb16afa83c858eb0869d8',
    messagingSenderId: '123422089993',
    projectId: 'lokaloka-3eeda',
    storageBucket: 'lokaloka-3eeda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmEBbJ8I8CYWtgijt7hgreRbKrrIi2mn4',
    appId: '1:123422089993:ios:da9fd15df9e587a50869d8',
    messagingSenderId: '123422089993',
    projectId: 'lokaloka-3eeda',
    storageBucket: 'lokaloka-3eeda.firebasestorage.app',
    androidClientId: '123422089993-a7nieopueqakrbe0661b16goeuso0luq.apps.googleusercontent.com',
    iosClientId: '123422089993-9c5alc3t1u83eqm2blhvad79v5kusib4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lokaloka',
  );
}
